apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: pojntfx/learn-chinese-platform-site
          ports:
            - containerPort: 9000
